image: gitpod/workspace-node-lts

tasks:
  - init: npm install
    command: npm start

ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true